global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'wls_exporter_metrics'
    scrape_interval: 10s
    metrics_path: /wls-exporter/metrics
    basic_auth:
      username: weblogic
      password: password
    static_configs:
      - targets: ['soahost-w1.vmware.com:7001']
      - targets: ['soahost-w1.vmware.com:8001']
      - targets: ['soahost-w2.vmware.com:8001']